[JENKINS-] Update auto-installed jdk version to jdk-8u144
jenkinsci/windows-slaves-plugin pull request #11
Opened 2017-10-17 14:51 UTC by dwnusbaum

See [JENKINS-47448](https://issues.jenkins-ci.org/browse/JENKINS-47448).

This updates the version of the JDK installed automatically when Java is not found from `jdk-6u16` to `jdk-8u144`.

@reviewbybees

2017-10-17 14:53 UTC, reviewbybees commented
This pull request originates from a [CloudBees](https://www.cloudbees.com/) employee. At CloudBees, we require that all pull requests be reviewed by other CloudBees employees before we seek to have the change accepted. If you want to learn more about our process please see [this explanation](https://github.com/reviewbybees/about#about-reviewbybees).

2017-10-17 15:34 UTC, oleg-nenashev requested changes
There is no `CPU.i386` anymore for JDK 8.x, only `i586`. I doubt the current patch may work, do you have test environment for that? If no, I could test in on Oct 30 when I return back from my current trip.

I would also support removing this feature though, but not in this release

2017-10-17 16:14 UTC, dwnusbaum commented
It looks like `CPU.i386` is used as a catch-all for architectures that aren't amd64, Sparc, or Itanium, and there is no `CPU.i586`. I'll test the patch on a 32-bit Windows machine to see the results.

* [Matching against JDK releases](https://github.com/dwnusbaum/jenkins/blob/36ef5d51cab5fb1a5c362ccfffcd120b88779252/core/src/main/java/hudson/tools/JDKInstaller.java#L645-L648)
* [Matching against current CPU](https://github.com/dwnusbaum/jenkins/blob/36ef5d51cab5fb1a5c362ccfffcd120b88779252/core/src/main/java/hudson/tools/JDKInstaller.java#L673)

I'll also update the code to use `CPU#of` to get the best architecture for the agent.

2017-10-18 08:48 UTC, aheritier requested changes
@dwnusbaum Your PR is already deprecated/broken, Oracle just released versions 151 and 152 thus the 144 is now in archives :(
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

2017-10-18 09:27 UTC, oleg-nenashev commented
Well, we are doing the best effort here.
@aheritier @dwnusbaum Is there a way to automatically determine the latest available version? If yes I will implement the logic which just picks the fresh version

2017-10-23 15:32 UTC, dwnusbaum commented
Current fix is already outdated, we need a sustainable solution.

2017-10-23 15:32 UTC, closed without merging