Rename binary
jenkinsci/windows-slaves-plugin pull request #17
Opened 2019-05-09 21:44 UTC by jsoref

See jenkinsci/jenkins@434135e

2019-05-09 22:08 UTC, jvz reviewed
I'm generally onboard with this. I'm not sure about any dependencies around releasing things for the renaming, though.

2019-05-09 22:14 UTC, oleg-nenashev commented
It would be nice to add a placeholder task in https://issues.jenkins-ci.org/browse/JENKINS-42816 so that we can track overall progress for "slave" leftovers. @jsoref if you see other changes missing in plugins, tickets will be also appreciated (especially newbie-friendly ones so that we can leave them to newcomers)

2019-05-09 22:18 UTC, oleg-nenashev requested changes
Thanks @jsoref ! I think it is important to land this change, but it should ensure that previously created agent services with "slave-..." continue working as is. Otherwise we risk serious collisions on the agent side since conflicting services might be created

2019-05-09 22:18 UTC, oleg-nenashev commented on src/main/resources/hudson/os/windows/ManagedWindowsServiceLauncher/config.properties
> +    This launch method relies on DCOM and is often associated with <a href="https://wiki.jenkins-ci.org/display/JENKINS/Windows+agents+fail+to+start+via+DCOM" target="_blank">subtle problems</a>. \
Wiki page has been already renamed, so we want to land it ASAP I'd guess

2019-05-09 22:18 UTC, oleg-nenashev commented on src/main/java/hudson/os/windows/ManagedWindowsServiceLauncher.java
> +    String generateServiceId(String agentRoot) throws IOException {
IIUC it will break existing services

2019-05-09 22:32 UTC, jsoref commented on src/main/java/hudson/os/windows/ManagedWindowsServiceLauncher.java
> +    String generateServiceId(String agentRoot) throws IOException {
Hmm... Looks like it needs to try both?

2019-05-09 23:01 UTC, jsoref commented on src/main/java/hudson/os/windows/ManagedWindowsServiceLauncher.java
> +    String generateServiceId(String agentRoot) throws IOException {
I think I've addressed this...

2019-07-26 12:53 UTC, oleg-nenashev commented
missed the notification

2019-12-30 10:30 UTC, oleg-nenashev commented on src/main/java/hudson/os/windows/ManagedWindowsServiceLauncher.java
> +    String generateServiceId(String agentRoot) throws IOException {
Looks so

2019-12-30 10:33 UTC, oleg-nenashev commented
Created https://issues.jenkins-ci.org/browse/JENKINS-60608

2019-12-30 10:34 UTC, oleg-nenashev commented on src/main/resources/hudson/os/windows/ManagedWindowsServiceLauncher/config.properties
> +    This launch method relies on DCOM and is often associated with <a href="https://wiki.jenkins-ci.org/display/JENKINS/Windows+agents+fail+to+start+via+DCOM" target="_blank">subtle problems</a>. \
I will fix it in a follow-up. Now it is https://github.com/jenkinsci/windows-slaves-plugin/blob/master/docs/troubleshooting.adoc

2019-12-30 10:34 UTC, oleg-nenashev approved these changes
I am approving it for the new release

2019-12-30 10:35 UTC, merged

2019-12-30 22:34 UTC, oleg-nenashev commented
Released it in https://github.com/jenkinsci/windows-slaves-plugin/releases/tag/windows-slaves-1.6